###
POST {{host}}/api/menus
Content-Type: application/json

{
  "name": "후라이드+후라이드",
  "price": 19000,
  "menuGroupId": "2bb9a5c9-1c0f-41ea-b8c5-ecebb87df543",
  "displayed": true,
  "menuProducts": [
    {
      "productId": "d5c45b35-0b5e-4633-9f83-ac650b1bbd54",
      "quantity": 2
    }
  ]
}

###
PUT {{host}}/api/menus/512a6871-4593-4711-bf7b-2ccdcfe7c181/price
Content-Type: application/json

{
  "price": 18000
}

###
PUT {{host}}/api/menus/512a6871-4593-4711-bf7b-2ccdcfe7c181/display

###
PUT {{host}}/api/menus/512a6871-4593-4711-bf7b-2ccdcfe7c181/hide

###
GET {{host}}/api/menus
