###
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "강정치킨",
  "price": 17000
}

###
PUT {{host}}/api/products/d5c45b35-0b5e-4633-9f83-ac650b1bbd54/price
Content-Type: application/json

{
  "price": 18000
}

###
GET {{host}}/api/products
