### 상품 생성
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "강정치킨",
  "price": 17000
}

### 상품 가격 조회
PUT {{host}}/api/products/3b528244-34f7-406b-bb7e-690912f66b10/price
Content-Type: application/json

{
  "price": 18000
}

### 상품 전체 조회
GET {{host}}/api/products
