###
GET {{host}}/api/tables

###
PUT {{host}}/api/tables/1/empty
Content-Type: application/json

{
  "empty": false
}

###
PUT {{host}}/api/tables/1/number-of-guests
Content-Type: application/json

{
  "numberOfGuests": 4
}

###
PUT {{host}}/api/tables/1/empty
Content-Type: application/json

{
  "empty": true
}

###
PUT {{host}}/api/tables/2/empty
Content-Type: application/json

{
  "empty": true
}

###
