SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE product;
TRUNCATE TABLE menu_group;
TRUNCATE TABLE menu;
TRUNCATE TABLE menu_product;
TRUNCATE TABLE product;
TRUNCATE TABLE order_table;
TRUNCATE TABLE orders;

SET REFERENTIAL_INTEGRITY TRUE;
